//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspAssignment.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Student
    {
        public int HNo { get; set; }
        [Required(ErrorMessage = "*")]
        public string Name { get; set; }
        [Required(ErrorMessage ="*")]
        public string Family_Name { get; set; }
        [Required(ErrorMessage ="*")]
        public string Address { get; set; }
        [Required(ErrorMessage ="*")]
        public string City { get; set; }
        [Required(ErrorMessage ="*")]
        public Nullable<int> Zip_code { get; set; }
        [Required(ErrorMessage ="*")]
        [MinLength(12,ErrorMessage ="(M0bile no should be 12 digit with country code)")]
        public string Phone { get; set; }
        [Required(ErrorMessage ="*")]
        [EmailAddress]
        public string Email { get; set; }
        
    }
}
