//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJack_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int GameNo { get; set; }
        public Nullable<int> PlayerTotal { get; set; }
        public Nullable<int> DealerTotal { get; set; }
        public string GameResult { get; set; }
    }
}
